approvals:
  # PR needs at least 1 approval
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  from:
    # commenter must be either one of:
    # a public Pazuzu org member
    orgs:
      - pazuzu-io
    # a collaborator of the repo
    collaborators: true
