version: '2'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    environment:
    - 'SPRING_APPLICATION_JSON={
        "spring": {
          "profiles": {
            "active": "dev"
          }
        }
      }'
