twintip:
  mapping: /api
  yaml: classpath:/api/swagger.yaml

spring:
  datasource:
    url: jdbc:hsqldb:mem:pazuzudb;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      show_sql: true
      format_sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: validate
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: ['classpath:db/migration', 'classpath:db/features', 'classpath:dev/db/provisioning']

management:
  server:
    servlet:
      context-path: /_manage
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

pazuzu:
  registry:
    cors:
      allowedOrigins: '*'


logging:
  level:
    org:
      hibernate:
        type: DEBUG
        tool:
          hbm2ddl: DEBUG
