tokens:
  autoStartup: false
  access-token-uri: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
  credentials-directory: ${user.home}/.berry/pazuzu-registry
  token-info-uri: https://info.services.auth.zalando.com/oauth2/tokeninfo
  token-configuration-list:
   - token-id: kio
     scopes:
      - uid

twintip:
  mapping: /api
  yaml: classpath:/api/swagger.yaml

security:
  basic:
    enabled: false

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgres-db:5432/postgres
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: validate

endpoints:
  enabled: false
  health:
    enabled: true
    path: /api/health
