twintip:
  mapping: /api
  yaml: classpath:/api/swagger.yaml

spring:
  datasource:
    url: jdbc:hsqldb:mem:pazuzudb;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: ['classpath:db/migration', 'classpath:db/features', 'classpath:dev/db/provisioning']

management:
  server:
    servlet:
      context-path: /_manage
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

pazuzu:
  registry:
    cors:
      allowedOrigins: '*'
