INSERT INTO FEATURE (NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, STATUS, AUTHOR, SNIPPET, TEST_SNIPPET) VALUES
  ('A', 'Java + Leiningen', now(), now(), 'APPROVED', 'Pazuzu team', NULL, NULL),
  ('B', 'Java + Node', now(), now(), 'APPROVED', 'Pazuzu team', NULL, NULL),
  ('C-A-B', 'A + B', now(), now(), 'APPROVED', 'Pazuzu team', NULL, NULL);

INSERT INTO FEATURE_DEPENDENCY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
  SELECT f.ID, d.ID FROM FEATURE f, FEATURE d WHERE f.NAME = 'A' AND d.NAME = 'java';

INSERT INTO FEATURE_DEPENDENCY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
  SELECT f.ID, d.ID FROM FEATURE f, FEATURE d WHERE f.NAME = 'A' AND d.NAME = 'leiningen';

INSERT INTO FEATURE_DEPENDENCY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
  SELECT f.ID, d.ID FROM FEATURE f, FEATURE d WHERE f.NAME = 'B' AND d.NAME = 'java';

INSERT INTO FEATURE_DEPENDENCY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
  SELECT f.ID, d.ID FROM FEATURE f, FEATURE d WHERE f.NAME = 'B' AND d.NAME = 'node';

INSERT INTO FEATURE_DEPENDENCY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
  SELECT f.ID, d.ID FROM FEATURE f, FEATURE d WHERE f.NAME = 'C-A-B' AND d.NAME = 'A';

INSERT INTO FEATURE_DEPENDENCY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
  SELECT f.ID, d.ID FROM FEATURE f, FEATURE d WHERE f.NAME = 'C-A-B' AND d.NAME = 'B';