CREATE TABLE REGISTRY (
  ID            INT           PRIMARY KEY,
  OWNER         VARCHAR(256)  NOT NULL,
  VERSION       VARCHAR(64)   NOT NULL,
  CREATED_AT    TIMESTAMP     NOT NULL,
  UPDATED_AT    TIMESTAMP     NOT NULL
);

INSERT INTO REGISTRY (ID, OWNER, VERSION, CREATED_AT, UPDATED_AT) VALUES
  (1, 'Pazuzu.io', '1.0.0', now(), now());