CREATE TABLE FEATURE (
  ID            SERIAL        PRIMARY KEY,
  FEATURE_NAME  VARCHAR(256)  NOT NULL,
  DOCKER_DATA   VARCHAR(4096) NOT NULL
);

CREATE TABLE CONTAINER (
  ID              SERIAL      PRIMARY KEY,
  CONTAINER_NAME  VARCHAR(32) NOT NULL
);

CREATE TABLE CONTAINER_FEATURE (
  CONTAINER_ID  INT     REFERENCES CONTAINER (ID),
  FEATURE_ID    INT     REFERENCES FEATURE (ID),
  PRIMARY KEY (CONTAINER_ID, FEATURE_ID)
);

CREATE TABLE FEATURE_DEPENDENCY (
  FEATURE_ID            INT     REFERENCES FEATURE (ID),
  DEPENDENCY_FEATURE_ID INT     REFERENCES FEATURE (ID),
  PRIMARY KEY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
);
