CREATE TABLE FEATURE (
  ID            SERIAL        PRIMARY KEY,
  NAME          VARCHAR(256)  NOT NULL UNIQUE,
  DESCRIPTION   TEXT          NULL,
  CREATED_AT    TIMESTAMP     NULL,
  UPDATED_AT    TIMESTAMP     NULL,
  AUTHOR        VARCHAR(256)  NULL,
  SNIPPET       TEXT          NULL,
  TEST_SNIPPET  TEXT          NULL
);

CREATE TABLE FEATURE_DEPENDENCY (
  FEATURE_ID            INT     REFERENCES FEATURE (ID),
  DEPENDENCY_FEATURE_ID INT     REFERENCES FEATURE (ID),
  PRIMARY KEY (FEATURE_ID, DEPENDENCY_FEATURE_ID)
);