DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS "category" CASCADE;
DROP TABLE IF EXISTS LANGUAGE_TYPE CASCADE;
DROP TABLE IF EXISTS LANGUAGE CASCADE;
DROP TABLE IF EXISTS FEATURE CASCADE;
DROP TABLE IF EXISTS FEATURE_BASE CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS FEATURE_USER CASCADE;


CREATE SEQUENCE HIBERNATE_SEQUENCE;

CREATE TABLE "user" (
  ID            BIGINT          PRIMARY KEY,
  USERNAME      VARCHAR(256)    NOT NULL UNIQUE,
  NAME          VARCHAR(256)    NOT NULL,
  EMAIL         VARCHAR(256)    NOT NULL UNIQUE
);

CREATE TABLE LANGUAGE_TYPE (
  ID            BIGINT          PRIMARY KEY,
  NAME          VARCHAR(256)    NOT NULL UNIQUE,
  DESCRIPTION   VARCHAR         NULL
);

CREATE TABLE LANGUAGE (
  ID            BIGINT          PRIMARY KEY,
  NAME          VARCHAR(256)    NOT NULL UNIQUE,
  DESCRIPTION   VARCHAR         NULL,
  CREATED_AT    TIMESTAMP       NULL,
  UPDATED_AT    TIMESTAMP       NULL,
  ACTIVE        BOOLEAN         NOT NULL,
  LANGUAGE_TYPE_ID  BIGINT      REFERENCES LANGUAGE_TYPE (ID)
);

CREATE TABLE FEATURE (
  ID            BIGINT          PRIMARY KEY,
  NAME          VARCHAR(256)    NOT NULL UNIQUE,
  DESCRIPTION   VARCHAR         NULL,
  CREATED_AT    TIMESTAMP       NULL,
  UPDATED_AT    TIMESTAMP       NULL,
  STATUS        VARCHAR(256)    NULL,
  ACTIVE        BOOLEAN         NULL,
  VERSION       VARCHAR(256)    NULL,
  AUTHOR_ID     BIGINT          REFERENCES "user"
);

CREATE TABLE "category" (
  ID            BIGINT          PRIMARY KEY,
  NAME          VARCHAR(256)    NOT NULL UNIQUE,
  DESCRIPTION   VARCHAR         NULL,
  CREATED_AT    TIMESTAMP       NULL,
  UPDATED_AT    TIMESTAMP       NULL,
  ACTIVE        BOOLEAN         NOT NULL,
  DEFAULT_FEATURE   BIGINT      REFERENCES FEATURE (ID),
  LANGUAGE_ID       BIGINT      REFERENCES LANGUAGE (ID)
);

ALTER TABLE FEATURE     ADD CATEGORY_ID   BIGINT           REFERENCES "category" (ID);
ALTER TABLE "category"  ADD PARENT_ID     BIGINT           REFERENCES "category" (ID);


CREATE TABLE FEATURE_USER (
  USER_ID       BIGINT         REFERENCES "user" (ID),
  FEATURE_ID    BIGINT         REFERENCES FEATURE (ID)
);

CREATE TABLE FEATURE_BASE (
  ID            BIGINT          PRIMARY KEY,
  NAME          VARCHAR(256)    NOT NULL UNIQUE,
  DESCRIPTION   VARCHAR         NULL
);

CREATE TABLE "group" (
  ID            BIGINT          PRIMARY KEY,
  NAME          VARCHAR(256)    NOT NULL UNIQUE,
  LANGUAGE_ID   BIGINT          REFERENCES LANGUAGE (ID)
);

CREATE TABLE SNIPPET (
  ID                BIGINT          PRIMARY KEY,
  NAME              VARCHAR(256)    NULL,
  DESCRIPTION       VARCHAR         NULL,
  CREATED_AT        TIMESTAMP       NULL,
  SNIPPET           VARCHAR         NULL,
  ACTIVE            BOOLEAN         NULL,
  CREATED_BY        BIGINT          REFERENCES "user" (ID)
);

CREATE TABLE FEATURE_LATEST (
  ID                BIGINT          PRIMARY KEY,
  FEATURE_ID        BIGINT          REFERENCES FEATURE (ID),
  SNIPPET_ID        BIGINT          REFERENCES SNIPPET (ID),
  BASE_ID           BIGINT          REFERENCES FEATURE_BASE (ID),
  CHANGED_AT        TIMESTAMP            NULL
);

CREATE TABLE "package" (
  ID                BIGINT          PRIMARY KEY,
  NAME              VARCHAR(256)    NOT NULL,
  VERSION              VARCHAR(256)    NULL
);

CREATE TABLE "resource" (
  ID                BIGINT          PRIMARY KEY,
  LOCATION          VARCHAR         NULL

);

CREATE TABLE TAG (
  ID                BIGINT          PRIMARY KEY,
  NAME              VARCHAR(256)    NOT NULL
);

CREATE TABLE SNIPPET_DEPENDENCY (
  SNIPPET_ID       BIGINT         REFERENCES SNIPPET (ID),
  DEPENDENCY_ID    BIGINT         REFERENCES SNIPPET (ID)
);

CREATE TABLE RESOURCE_DEPENDENCY (
  SNIPPET_ID       BIGINT         REFERENCES SNIPPET (ID),
  DEPENDENCY_ID    BIGINT         REFERENCES "resource" (ID)
);

CREATE TABLE PACKAGE_DEPENDENCY (
  SNIPPET_ID       BIGINT         REFERENCES SNIPPET (ID),
  DEPENDENCY_ID    BIGINT         REFERENCES "package" (ID)
);

CREATE TABLE FEATURE_REQUEST (
  ID                BIGINT          PRIMARY KEY
);

CREATE TABLE FEATURE_REQUEST_STATUS (
  ID                BIGINT          PRIMARY KEY
);






