CREATE TABLE TAG (
  ID  SERIAL  PRIMARY KEY,
  TAG_NAME  VARCHAR(32) NOT NULL
);

CREATE TABLE FEATURE_TAGS (
  ID  SERIAL  PRIMARY KEY,
  FEATURE_ID  INT REFERENCES FEATURE (ID),
  TAGS_ID INT  REFERENCES TAG (ID)
);