ALTER TABLE FEATURE
  RENAME COLUMN FEATURE_NAME TO NAME;
ALTER TABLE FEATURE
  ADD COLUMN SNIPPET VARCHAR(4096) NULL;
ALTER TABLE FEATURE
  RENAME COLUMN TEST_INSTRUCTION TO TEST_SNIPPET;
ALTER TABLE FEATURE
  ADD COLUMN AUTHOR VARCHAR(256) NULL;
ALTER TABLE FEATURE
  ADD COLUMN UPDATED_AT TIMESTAMP NULL;

UPDATE FEATURE SET SNIPPET = DOCKER_DATA WHERE TRUE;

ALTER TABLE FEATURE
  DROP COLUMN DOCKER_DATA;
